---
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# The code used in this section was adapted from https://ftp.yz.yamagata-u.ac.jp/pub/cran/web/packages/geocmeans/vignettes/introduction.html

# Library
```{r}
#charging packages and data
library(sf)
library(geocmeans)
library(ggplot2)
library(ggpubr)
library(dplyr)
library(viridis)
library(spdep)
```
# Pre NonFire

```{r}
iNat_AnalysisFields <- c("avg_positional_accuracy","avg_quality_grade","avg_agreement_score","avg_datediff","aves_count","plantae_count","fungi_count","animalia_count","insecta_count","other_count","arachnida_count","reptilia_count","mammalia_count","mollusca_count","chromista_count","amphibia_count","actinopterygii_count","protozoa_count")

#rescaling the columns
iNat_Cluster_Poly_PreNonFire_CPAD_Only <- iNat_PreNonFire_CPAD_Only_Grids[iNat_AnalysisFields]

iNat_Cluster_Poly_PreNonFire_CPAD_Only <- as_Spatial(iNat_Cluster_Poly_PreNonFire_CPAD_Only)

iNat_Cluster_PreNonFire_CPAD_Only <- iNat_Cluster_Poly_PreNonFire_CPAD_Only@data[iNat_AnalysisFields]
for (Col in names(iNat_Cluster_PreNonFire_CPAD_Only)){
  iNat_Cluster_PreNonFire_CPAD_Only[[Col]] <- scale(iNat_Cluster_PreNonFire_CPAD_Only[[Col]])
}

iNat_Cluster_PreNonFire_CPAD_Only$plantae_count <- 0
iNat_Cluster_PreNonFire_CPAD_Only$other_count <- 0
iNat_Cluster_PreNonFire_CPAD_Only$mollusca_count <- 0
iNat_Cluster_PreNonFire_CPAD_Only$chromista_count <- 0
iNat_Cluster_PreNonFire_CPAD_Only$protozoa_count <- 0

Neighbours <- poly2nb(iNat_Cluster_Poly_PreNonFire_CPAD_Only, queen = TRUE)
WMat <- nb2listw(Neighbours, style = "W", zero.policy = TRUE)

#preparing some elements for further mapping
iNat_Cluster_Poly_PreNonFire_CPAD_Only$OID <- as.character(1:nrow(iNat_Cluster_Poly_PreNonFire_CPAD_Only))

FortiData <- broom::tidy(iNat_Cluster_Poly_PreNonFire_CPAD_Only,region="OID")

iNat_Cluster_PreNonFire_CPAD_Only_SGFCM <- SGFCMeans(iNat_Cluster_PreNonFire_CPAD_Only,WMat,k = 4,m=1.5, alpha=0.95, beta = 0.65,
                                                  tol=0.0001, standardize = FALSE, verbose = FALSE, seed = 456)

SGFCMMaps <- mapClusters(geodata = iNat_Cluster_Poly_PreNonFire_CPAD_Only, object = iNat_Cluster_PreNonFire_CPAD_Only_SGFCM$Belongings,undecided = 0.45)
```

```{r}
ggarrange(SGFCMMaps$ProbaMaps[[1]], nrow = 1, ncol = 1,
          common.legend = TRUE, legend = "bottom")

ggarrange(SGFCMMaps$ProbaMaps[[2]], nrow = 1, ncol = 1,
          common.legend = TRUE, legend = "bottom")

ggarrange(SGFCMMaps$ProbaMaps[[3]], nrow = 1, ncol = 1,
          common.legend = TRUE, legend = "bottom")

ggarrange(SGFCMMaps$ProbaMaps[[4]], nrow = 1, ncol = 1,
          common.legend = TRUE, legend = "bottom")

# Final map
Undecided <- undecidedUnits(iNat_Cluster_PreNonFire_CPAD_Only_SGFCM$Belongings,0.45)
iNat_Cluster_Poly_PreNonFire_CPAD_Only$FinalCluster <- ifelse(Undecided=="Undecided",
                                                           "Undecided",paste("cluster",Undecided,sep="_"))

#mapping the groups
DFmapping <- merge(FortiData,iNat_Cluster_Poly_PreNonFire_CPAD_Only,by.x="id",by.y="OID")

ggplot(data=DFmapping)+
  geom_polygon(aes(x=long,y=lat,group=group,fill=FinalCluster),color=rgb(0,0,0,0))+
  coord_fixed(ratio = 1)+
  ggtitle("iNat_PreNonFire_CPAD_Only_FinalCluster") +
  scale_fill_manual(name="Clusters",values = c("cluster_V1"="palegreen3",
                                               "cluster_V2"="Firebrick",
                                               "cluster_V3"="yellow",
                                               "cluster_V4"="steelblue",
                                               "Undecided"=rgb(0,0,0,0.4)))+
  theme( axis.title = element_blank(),
         axis.text = element_blank(),
         axis.ticks = element_blank()
  )
```

```{r}
#summarizeClusters(iNat_Cluster_PreNonFire_CPAD_Only,belongmatrix = iNat_Cluster_PreNonFire_CPAD_Only_SGFCM$Belongings,
#                  weighted = TRUE, dec = 3)

spiderPlots(iNat_Cluster_PreNonFire_CPAD_Only, iNat_Cluster_PreNonFire_CPAD_Only_SGFCM$Belongings,
            chartcolors = c("palegreen3","Firebrick","yellow","steelblue"))
title("iNat_PreNonFire_CPAD_Only clusters and input variables")
```

```{r}
bootvalues <- boot_group_validation(iNat_Cluster_PreNonFire_CPAD_Only_SGFCM, nsim = 1000, maxiter = 1000, 
                                    tol = 0.0001, verbose = FALSE)

melted_df <- reshape2::melt(bootvalues$group_consistency)

melted_df$variable <- as.factor(melted_df$variable)

ggplot() +
  geom_histogram(mapping = aes(x = value), data = melted_df, bins = 30) +
  labs(title = "stability of clusters for iNat_PreNonFire_CPAD_Only", subtitle = "for 1000 iterations",
       x = "Jaccard index") +
  facet_wrap(vars(variable), ncol=2) +
  geom_vline(xintercept = 0.5, linetype="dotted", 
                color = "red", size=1)
```

```{r, fig.width = 10, fig.height= 10}
# groups 2 and 4 raised as concerns 

df_gp1 <- bootvalues$group_centers[["group1"]]

melted_df <- reshape2::melt(df_gp1)

melted_df$variable <- as.factor(melted_df$variable)

ggplot() +
  geom_histogram(mapping = aes(x = value), data = melted_df, bins = 30) +
  labs(title = "stability of group 1 centers for iNat_PreNonFire_CPAD_Only", subtitle = "for 1000 iterations") +
  xlim(-3,3)+
  facet_wrap(vars(variable), ncol=3)+
  geom_vline(xintercept = 0.5, linetype="dotted", 
                color = "red", size=1)

df_gp2 <- bootvalues$group_centers[["group2"]]

melted_df <- reshape2::melt(df_gp2)

melted_df$variable <- as.factor(melted_df$variable)

ggplot() +
  geom_histogram(mapping = aes(x = value), data = melted_df, bins = 30) +
  labs(title = "stability of group 2 centers for iNat_PreNonFire_CPAD_Only", subtitle = "for 1000 iterations") +
  xlim(-3,3)+
  facet_wrap(vars(variable), ncol=3)+
  geom_vline(xintercept = 0.5, linetype="dotted", 
                color = "red", size=1)

df_gp3 <- bootvalues$group_centers[["group3"]]

melted_df <- reshape2::melt(df_gp3)

melted_df$variable <- as.factor(melted_df$variable)

ggplot() +
  geom_histogram(mapping = aes(x = value), data = melted_df, bins = 30) +
  labs(title = "stability of group 3 centers for iNat_PreNonFire_CPAD_Only", subtitle = "for 1000 iterations") +
  xlim(-3,3)+
  facet_wrap(vars(variable), ncol=3)+
  geom_vline(xintercept = 0.5, linetype="dotted", 
                color = "red", size=1)

df_gp4 <- bootvalues$group_centers[["group4"]]

melted_df <- reshape2::melt(df_gp4)

melted_df$variable <- as.factor(melted_df$variable)

ggplot() +
  geom_histogram(mapping = aes(x = value), data = melted_df, bins = 30) +
  labs(title = "stability of group 4 centers for iNat_PreNonFire_CPAD_Only", subtitle = "for 1000 iterations") +
  xlim(-3,3)+
  facet_wrap(vars(variable), ncol=3)+
  geom_vline(xintercept = 0.5, linetype="dotted", 
                color = "red", size=1)
```

```{r}
rm(DFmapping,FortiData,Undecided,SGFCMMaps,WMat,Neighbours,bootvalues,melted_df,df_gp1,df_gp2,df_gp3,df_gp4)
```

# NonFire

```{r}
iNat_AnalysisFields <- c("avg_positional_accuracy","avg_quality_grade","avg_agreement_score","avg_datediff","aves_count","plantae_count","fungi_count","animalia_count","insecta_count","other_count","arachnida_count","reptilia_count","mammalia_count","mollusca_count","chromista_count","amphibia_count","actinopterygii_count","protozoa_count")

#rescaling the columns
iNat_Cluster_Poly_NonFire_CPAD_Only <- iNat_NonFire_CPAD_Only_Grids[iNat_AnalysisFields]

iNat_Cluster_Poly_NonFire_CPAD_Only <- as_Spatial(iNat_Cluster_Poly_NonFire_CPAD_Only)

iNat_Cluster_NonFire_CPAD_Only <- iNat_Cluster_Poly_NonFire_CPAD_Only@data[iNat_AnalysisFields]
for (Col in names(iNat_Cluster_NonFire_CPAD_Only)){
  iNat_Cluster_NonFire_CPAD_Only[[Col]] <- scale(iNat_Cluster_NonFire_CPAD_Only[[Col]])
}

iNat_Cluster_NonFire_CPAD_Only$plantae_count <- 0
iNat_Cluster_NonFire_CPAD_Only$fungi_count <- 0
iNat_Cluster_NonFire_CPAD_Only$other_count <- 0
iNat_Cluster_NonFire_CPAD_Only$mollusca_count <- 0
iNat_Cluster_NonFire_CPAD_Only$chromista_count <- 0
iNat_Cluster_NonFire_CPAD_Only$amphibia_count <- 0
iNat_Cluster_NonFire_CPAD_Only$actinopterygii_count <- 0
iNat_Cluster_NonFire_CPAD_Only$protozoa_count <- 0


Neighbours <- poly2nb(iNat_Cluster_Poly_NonFire_CPAD_Only, queen = TRUE)
WMat <- nb2listw(Neighbours, style = "W", zero.policy = TRUE)

#preparing some elements for further mapping
iNat_Cluster_Poly_NonFire_CPAD_Only$OID <- as.character(1:nrow(iNat_Cluster_Poly_NonFire_CPAD_Only))

FortiData <- broom::tidy(iNat_Cluster_Poly_NonFire_CPAD_Only,region="OID")

iNat_Cluster_NonFire_CPAD_Only_SGFCM <- SGFCMeans(iNat_Cluster_NonFire_CPAD_Only,WMat,k = 4,m=1.5, alpha=0.95, beta = 0.65,
                                                  tol=0.0001, standardize = FALSE, verbose = FALSE, seed = 456)

SGFCMMaps <- mapClusters(geodata = iNat_Cluster_Poly_NonFire_CPAD_Only, object = iNat_Cluster_NonFire_CPAD_Only_SGFCM$Belongings,undecided = 0.45)
```

```{r}
ggarrange(SGFCMMaps$ProbaMaps[[1]], nrow = 1, ncol = 1,
          common.legend = TRUE, legend = "bottom")

ggarrange(SGFCMMaps$ProbaMaps[[2]], nrow = 1, ncol = 1,
          common.legend = TRUE, legend = "bottom")

ggarrange(SGFCMMaps$ProbaMaps[[3]], nrow = 1, ncol = 1,
          common.legend = TRUE, legend = "bottom")

ggarrange(SGFCMMaps$ProbaMaps[[4]], nrow = 1, ncol = 1,
          common.legend = TRUE, legend = "bottom")

# Final map
Undecided <- undecidedUnits(iNat_Cluster_NonFire_CPAD_Only_SGFCM$Belongings,0.45)
iNat_Cluster_Poly_NonFire_CPAD_Only$FinalCluster <- ifelse(Undecided=="Undecided",
                                                           "Undecided",paste("cluster",Undecided,sep="_"))

#mapping the groups
DFmapping <- merge(FortiData,iNat_Cluster_Poly_NonFire_CPAD_Only,by.x="id",by.y="OID")

ggplot(data=DFmapping)+
  geom_polygon(aes(x=long,y=lat,group=group,fill=FinalCluster),color=rgb(0,0,0,0))+
  coord_fixed(ratio = 1)+
  ggtitle("iNat_NonFire_CPAD_Only_FinalCluster") +
  scale_fill_manual(name="Clusters",values = c("cluster_V1"="palegreen3",
                                               "cluster_V2"="Firebrick",
                                               "cluster_V3"="yellow",
                                               "cluster_V4"="steelblue",
                                               "Undecided"=rgb(0,0,0,0.4)))+
  theme( axis.title = element_blank(),
         axis.text = element_blank(),
         axis.ticks = element_blank()
  )
```

```{r}
#summarizeClusters(iNat_Cluster_NonFire_CPAD_Only,belongmatrix = iNat_Cluster_NonFire_CPAD_Only_SGFCM$Belongings,
#                  weighted = TRUE, dec = 3)

spiderPlots(iNat_Cluster_NonFire_CPAD_Only, iNat_Cluster_NonFire_CPAD_Only_SGFCM$Belongings,
            chartcolors = c("palegreen3","Firebrick","yellow","steelblue"))
title("iNat_NonFire_CPAD_Only clusters and input variables")
```

```{r}
bootvalues <- boot_group_validation(iNat_Cluster_NonFire_CPAD_Only_SGFCM, nsim = 1000, maxiter = 1000, 
                                    tol = 0.0001, verbose = FALSE)

melted_df <- reshape2::melt(bootvalues$group_consistency)

melted_df$variable <- as.factor(melted_df$variable)

ggplot() +
  geom_histogram(mapping = aes(x = value), data = melted_df, bins = 30) +
  labs(title = "stability of clusters for iNat_NonFire_CPAD_Only", subtitle = "for 1000 iterations",
       x = "Jaccard index") +
  facet_wrap(vars(variable), ncol=2) +
  geom_vline(xintercept = 0.5, linetype="dotted", 
             color = "red", size=1)
```

```{r, fig.width = 10, fig.height= 10}
# groups 2 and 4 raised as concerns 

df_gp1 <- bootvalues$group_centers[["group1"]]

melted_df <- reshape2::melt(df_gp1)

melted_df$variable <- as.factor(melted_df$variable)

ggplot() +
  geom_histogram(mapping = aes(x = value), data = melted_df, bins = 30) +
  labs(title = "stability of group 1 centers for iNat_NonFire_CPAD_Only", subtitle = "for 1000 iterations") +
  xlim(-3,3)+
  facet_wrap(vars(variable), ncol=3)+
  geom_vline(xintercept = 0.5, linetype="dotted", 
             color = "red", size=1)

df_gp2 <- bootvalues$group_centers[["group2"]]

melted_df <- reshape2::melt(df_gp2)

melted_df$variable <- as.factor(melted_df$variable)

ggplot() +
  geom_histogram(mapping = aes(x = value), data = melted_df, bins = 30) +
  labs(title = "stability of group 2 centers for iNat_NonFire_CPAD_Only", subtitle = "for 1000 iterations") +
  xlim(-3,3)+
  facet_wrap(vars(variable), ncol=3)+
  geom_vline(xintercept = 0.5, linetype="dotted", 
             color = "red", size=1)

df_gp3 <- bootvalues$group_centers[["group3"]]

melted_df <- reshape2::melt(df_gp3)

melted_df$variable <- as.factor(melted_df$variable)

ggplot() +
  geom_histogram(mapping = aes(x = value), data = melted_df, bins = 30) +
  labs(title = "stability of group 3 centers for iNat_NonFire_CPAD_Only", subtitle = "for 1000 iterations") +
  xlim(-3,3)+
  facet_wrap(vars(variable), ncol=3)+
  geom_vline(xintercept = 0.5, linetype="dotted", 
             color = "red", size=1)

df_gp4 <- bootvalues$group_centers[["group4"]]

melted_df <- reshape2::melt(df_gp4)

melted_df$variable <- as.factor(melted_df$variable)

ggplot() +
  geom_histogram(mapping = aes(x = value), data = melted_df, bins = 30) +
  labs(title = "stability of group 4 centers for iNat_NonFire_CPAD_Only", subtitle = "for 1000 iterations") +
  xlim(-3,3)+
  facet_wrap(vars(variable), ncol=3)+
  geom_vline(xintercept = 0.5, linetype="dotted", 
             color = "red", size=1)
```

```{r}
rm(DFmapping,FortiData,Undecided,SGFCMMaps,WMat,Neighbours,bootvalues,melted_df,df_gp1,df_gp2,df_gp3,df_gp4)
```

# Post NonFire

```{r}
iNat_AnalysisFields <- c("avg_positional_accuracy","avg_quality_grade","avg_agreement_score","avg_datediff","aves_count","plantae_count","fungi_count","animalia_count","insecta_count","other_count","arachnida_count","reptilia_count","mammalia_count","mollusca_count","chromista_count","amphibia_count","actinopterygii_count","protozoa_count")

#rescaling the columns
iNat_Cluster_Poly_PostNonFire_CPAD_Only <- iNat_PostNonFire_CPAD_Only_Grids[iNat_AnalysisFields]

iNat_Cluster_Poly_PostNonFire_CPAD_Only <- as_Spatial(iNat_Cluster_Poly_PostNonFire_CPAD_Only)

iNat_Cluster_PostNonFire_CPAD_Only <- iNat_Cluster_Poly_PostNonFire_CPAD_Only@data[iNat_AnalysisFields]
for (Col in names(iNat_Cluster_PostNonFire_CPAD_Only)){
  iNat_Cluster_PostNonFire_CPAD_Only[[Col]] <- scale(iNat_Cluster_PostNonFire_CPAD_Only[[Col]])
}

iNat_Cluster_PostNonFire_CPAD_Only$plantae_count <- 0
iNat_Cluster_PostNonFire_CPAD_Only$animalia_count <- 0
iNat_Cluster_PostNonFire_CPAD_Only$other_count <- 0
iNat_Cluster_PostNonFire_CPAD_Only$arachnida_count <- 0
iNat_Cluster_PostNonFire_CPAD_Only$chromista_count <- 0
iNat_Cluster_PostNonFire_CPAD_Only$amphibia_count <- 0
iNat_Cluster_PostNonFire_CPAD_Only$actinopterygii_count <- 0
iNat_Cluster_PostNonFire_CPAD_Only$protozoa_count <- 0

Neighbours <- poly2nb(iNat_Cluster_Poly_PostNonFire_CPAD_Only, queen = TRUE)
WMat <- nb2listw(Neighbours, style = "W", zero.policy = TRUE)

#preparing some elements for further mapping
iNat_Cluster_Poly_PostNonFire_CPAD_Only$OID <- as.character(1:nrow(iNat_Cluster_Poly_PostNonFire_CPAD_Only))

FortiData <- broom::tidy(iNat_Cluster_Poly_PostNonFire_CPAD_Only,region="OID")

iNat_Cluster_PostNonFire_CPAD_Only_SGFCM <- SGFCMeans(iNat_Cluster_PostNonFire_CPAD_Only,WMat,k = 4,m=1.5, alpha=0.95, beta = 0.65,
                                                  tol=0.0001, standardize = FALSE, verbose = FALSE, seed = 456)

SGFCMMaps <- mapClusters(geodata = iNat_Cluster_Poly_PostNonFire_CPAD_Only, object = iNat_Cluster_PostNonFire_CPAD_Only_SGFCM$Belongings,undecided = 0.45)
```

```{r}
ggarrange(SGFCMMaps$ProbaMaps[[1]], nrow = 1, ncol = 1,
          common.legend = TRUE, legend = "bottom")

ggarrange(SGFCMMaps$ProbaMaps[[2]], nrow = 1, ncol = 1,
          common.legend = TRUE, legend = "bottom")

ggarrange(SGFCMMaps$ProbaMaps[[3]], nrow = 1, ncol = 1,
          common.legend = TRUE, legend = "bottom")

ggarrange(SGFCMMaps$ProbaMaps[[4]], nrow = 1, ncol = 1,
          common.legend = TRUE, legend = "bottom")

# Final map
Undecided <- undecidedUnits(iNat_Cluster_PostNonFire_CPAD_Only_SGFCM$Belongings,0.45)
iNat_Cluster_Poly_PostNonFire_CPAD_Only$FinalCluster <- ifelse(Undecided=="Undecided",
                                                           "Undecided",paste("cluster",Undecided,sep="_"))

#mapping the groups
DFmapping <- merge(FortiData,iNat_Cluster_Poly_PostNonFire_CPAD_Only,by.x="id",by.y="OID")

ggplot(data=DFmapping)+
  geom_polygon(aes(x=long,y=lat,group=group,fill=FinalCluster),color=rgb(0,0,0,0))+
  coord_fixed(ratio = 1)+
  ggtitle("iNat_PostNonFire_CPAD_Only_FinalCluster") +
  scale_fill_manual(name="Clusters",values = c("cluster_V1"="palegreen3",
                                               "cluster_V2"="Firebrick",
                                               "cluster_V3"="yellow",
                                               "cluster_V4"="steelblue",
                                               "Undecided"=rgb(0,0,0,0.4)))+
  theme( axis.title = element_blank(),
         axis.text = element_blank(),
         axis.ticks = element_blank()
  )
```

```{r}
#summarizeClusters(iNat_Cluster_PostNonFire_CPAD_Only,belongmatrix = iNat_Cluster_PostNonFire_CPAD_Only_SGFCM$Belongings,
#                  weighted = TRUE, dec = 3)

spiderPlots(iNat_Cluster_PostNonFire_CPAD_Only, iNat_Cluster_PostNonFire_CPAD_Only_SGFCM$Belongings,
            chartcolors = c("palegreen3","Firebrick","yellow","steelblue"))
title("iNat_PostNonFire_CPAD_Only clusters and input variables")
```

```{r}
bootvalues <- boot_group_validation(iNat_Cluster_PostNonFire_CPAD_Only_SGFCM, nsim = 1000, maxiter = 1000, 
                                    tol = 0.0001, verbose = FALSE)

melted_df <- reshape2::melt(bootvalues$group_consistency)

melted_df$variable <- as.factor(melted_df$variable)

ggplot() +
  geom_histogram(mapping = aes(x = value), data = melted_df, bins = 30) +
  labs(title = "stability of clusters for iNat_PostNonFire_CPAD_Only", subtitle = "for 1000 iterations",
       x = "Jaccard index") +
  facet_wrap(vars(variable), ncol=2) +
  geom_vline(xintercept = 0.5, linetype="dotted", 
             color = "red", size=1)
```

```{r, fig.width = 10, fig.height= 10}
# groups 2 and 4 raised as concerns 

df_gp1 <- bootvalues$group_centers[["group1"]]

melted_df <- reshape2::melt(df_gp1)

melted_df$variable <- as.factor(melted_df$variable)

ggplot() +
  geom_histogram(mapping = aes(x = value), data = melted_df, bins = 30) +
  labs(title = "stability of group 1 centers for iNat_PostNonFire_CPAD_Only", subtitle = "for 1000 iterations") +
  xlim(-3,3)+
  facet_wrap(vars(variable), ncol=3)+
  geom_vline(xintercept = 0.5, linetype="dotted", 
             color = "red", size=1)

df_gp2 <- bootvalues$group_centers[["group2"]]

melted_df <- reshape2::melt(df_gp2)

melted_df$variable <- as.factor(melted_df$variable)

ggplot() +
  geom_histogram(mapping = aes(x = value), data = melted_df, bins = 30) +
  labs(title = "stability of group 2 centers for iNat_PostNonFire_CPAD_Only", subtitle = "for 1000 iterations") +
  xlim(-3,3)+
  facet_wrap(vars(variable), ncol=3)+
  geom_vline(xintercept = 0.5, linetype="dotted", 
             color = "red", size=1)

df_gp3 <- bootvalues$group_centers[["group3"]]

melted_df <- reshape2::melt(df_gp3)

melted_df$variable <- as.factor(melted_df$variable)

ggplot() +
  geom_histogram(mapping = aes(x = value), data = melted_df, bins = 30) +
  labs(title = "stability of group 3 centers for iNat_PostNonFire_CPAD_Only", subtitle = "for 1000 iterations") +
  xlim(-3,3)+
  facet_wrap(vars(variable), ncol=3)+
  geom_vline(xintercept = 0.5, linetype="dotted", 
             color = "red", size=1)

df_gp4 <- bootvalues$group_centers[["group4"]]

melted_df <- reshape2::melt(df_gp4)

melted_df$variable <- as.factor(melted_df$variable)

ggplot() +
  geom_histogram(mapping = aes(x = value), data = melted_df, bins = 30) +
  labs(title = "stability of group 4 centers for iNat_PostNonFire_CPAD_Only", subtitle = "for 1000 iterations") +
  xlim(-3,3)+
  facet_wrap(vars(variable), ncol=3)+
  geom_vline(xintercept = 0.5, linetype="dotted", 
             color = "red", size=1)
```

```{r}
rm(DFmapping,FortiData,Undecided,SGFCMMaps,WMat,Neighbours,bootvalues,melted_df,df_gp1,df_gp2,df_gp3,df_gp4)
```