---
  output: pdf_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# The code used in this section was adapted from https://ftp.yz.yamagata-u.ac.jp/pub/cran/web/packages/geocmeans/vignettes/introduction.html

# Library
```{r}
library(sf)
library(geocmeans)
library(ggplot2)
library(ggpubr)
library(dplyr)
library(viridis)
library(spdep)
```

# Pre Fire

#Prepare the data
```{r}
# Define Fields
OSM_AnalysisFields <- c("avg_version","avg_NACount", "avg_datediff", "aeroway_count","amenity_count","barrier_count","boundary_count","building_count","emergency_count","highway_count","historic_count","landuse_count","leisure_count","man_made_count","natural_count","office_count","place_count","power_count","railway_count","route_count","shop_count","sport_count","tourism_count","water_count","waterway_count")

#rescaling the columns
OSM_Cluster_Poly_PreFire_Neither <- OSM_PreFire_Neither_Grids[OSM_AnalysisFields]

# Make file spatial
OSM_Cluster_Poly_PreFire_Neither <- as_Spatial(OSM_Cluster_Poly_PreFire_Neither)

# Reformat data
OSM_Cluster_PreFire_Neither <- OSM_Cluster_Poly_PreFire_Neither@data[OSM_AnalysisFields]
for (Col in names(OSM_Cluster_PreFire_Neither)){
  OSM_Cluster_PreFire_Neither[[Col]] <- scale(OSM_Cluster_PreFire_Neither[[Col]])
}

# Make N/A columns 0
OSM_Cluster_PreFire_Neither$aeroway_count <- 0
OSM_Cluster_PreFire_Neither$amenity_count <- 0
OSM_Cluster_PreFire_Neither$barrier_count <- 0
OSM_Cluster_PreFire_Neither$boundary_count <- 0
OSM_Cluster_PreFire_Neither$building_count <- 0
OSM_Cluster_PreFire_Neither$emergency_count <- 0
OSM_Cluster_PreFire_Neither$historic_count <- 0
OSM_Cluster_PreFire_Neither$landuse_count <- 0
OSM_Cluster_PreFire_Neither$leisure_count <- 0
OSM_Cluster_PreFire_Neither$man_made_count <- 0
OSM_Cluster_PreFire_Neither$office_count <- 0
OSM_Cluster_PreFire_Neither$place_count <- 0
OSM_Cluster_PreFire_Neither$power_count <- 0
OSM_Cluster_PreFire_Neither$railway_count <- 0
OSM_Cluster_PreFire_Neither$shop_count <- 0
OSM_Cluster_PreFire_Neither$sport_count <- 0
OSM_Cluster_PreFire_Neither$tourism_count <- 0
OSM_Cluster_PreFire_Neither$water_count <- 0

# Calculate Queen Neighbours
Neighbours <- poly2nb(OSM_Cluster_Poly_PreFire_Neither, queen = TRUE)
WMat <- nb2listw(Neighbours, style = "W", zero.policy = TRUE)

#preparing some elements for further mapping
OSM_Cluster_Poly_PreFire_Neither$OID <- as.character(1:nrow(OSM_Cluster_Poly_PreFire_Neither))
FortiData <- broom::tidy(OSM_Cluster_Poly_PreFire_Neither,region="OID")

# Calculate SGFCM
OSM_Cluster_PreFire_Neither_SGFCM <- SGFCMeans(OSM_Cluster_PreFire_Neither,WMat,k = 4,m=1.5, alpha=0.95, beta = 0.65,
                                             tol=0.0001, standardize = FALSE, verbose = FALSE, seed = 456)
# Make a cluster map
SGFCMMaps <- mapClusters(geodata = OSM_Cluster_Poly_PreFire_Neither, object = OSM_Cluster_PreFire_Neither_SGFCM$Belongings,undecided = 0.45)
```

# Maps
```{r}
# Plot a map per cluster value
ggarrange(SGFCMMaps$ProbaMaps[[1]], nrow = 1, ncol = 1,
          common.legend = TRUE, legend = "bottom")

ggarrange(SGFCMMaps$ProbaMaps[[2]], nrow = 1, ncol = 1,
          common.legend = TRUE, legend = "bottom")

ggarrange(SGFCMMaps$ProbaMaps[[3]], nrow = 1, ncol = 1,
          common.legend = TRUE, legend = "bottom")

ggarrange(SGFCMMaps$ProbaMaps[[4]], nrow = 1, ncol = 1,
          common.legend = TRUE, legend = "bottom")

# Plot the Final map
# Ensure all values below 0.45 are in undecided
Undecided <- undecidedUnits(OSM_Cluster_PreFire_Neither_SGFCM$Belongings,0.45)
OSM_Cluster_Poly_PreFire_Neither$FinalCluster <- ifelse(Undecided=="Undecided",
                                                      "Undecided",paste("cluster",Undecided,sep="_"))

#mapping the groups
DFmapping <- merge(FortiData,OSM_Cluster_Poly_PreFire_Neither,by.x="id",by.y="OID")

ggplot(data=DFmapping)+
  geom_polygon(aes(x=long,y=lat,group=group,fill=FinalCluster),color=rgb(0,0,0,0))+
  coord_fixed(ratio = 1)+
  ggtitle("OSM_PreFire_Neither_FinalCluster") +
  scale_fill_manual(name="Clusters",values = c("cluster_V1"="palegreen3",
                                               "cluster_V2"="Firebrick",
                                               "cluster_V3"="yellow",
                                               "cluster_V4"="steelblue",
                                               "Undecided"=rgb(0,0,0,0.4)))+
  theme( axis.title = element_blank(),
         axis.text = element_blank(),
         axis.ticks = element_blank()
  )
```

# Spider plots
```{r}
spiderPlots(OSM_Cluster_PreFire_Neither, OSM_Cluster_PreFire_Neither_SGFCM$Belongings,
            chartcolors = c("palegreen3","Firebrick","yellow","steelblue"))
title("OSM_PreFire_Neither clusters and input variables")
```

# Stability Checks on Clusters
```{r}
# Find the jaccard index stability values
bootvalues <- boot_group_validation(OSM_Cluster_PreFire_Neither_SGFCM, nsim = 1000, maxiter = 1000, 
                                    tol = 0.0001, verbose = FALSE)

melted_df <- reshape2::melt(bootvalues$group_consistency)
melted_df$variable <- as.factor(melted_df$variable)

# Plot the map
ggplot() +
  geom_histogram(mapping = aes(x = value), data = melted_df, bins = 30) +
  labs(title = "stability of clusters for OSM_PreFire_Neither", subtitle = "for 1000 iterations",
       x = "Jaccard index") +
  facet_wrap(vars(variable), ncol=2) +
  geom_vline(xintercept = 0.5, linetype="dotted", 
             color = "red", size=1)
```

# Stability checks on input variables
```{r, fig.width = 10, fig.height= 10}
# Repeat Steps from previous section for all groups or clusters

df_gp1 <- bootvalues$group_centers[["group1"]]

melted_df <- reshape2::melt(df_gp1)
melted_df$variable <- as.factor(melted_df$variable)

ggplot() +
  geom_histogram(mapping = aes(x = value), data = melted_df, bins = 30) +
  labs(title = "stability of group 1 centers for OSM_PreFire_Neither", subtitle = "for 1000 iterations") +
  xlim(-3,3)+
  facet_wrap(vars(variable), ncol=3)+
  geom_vline(xintercept = 0.5, linetype="dotted", 
             color = "red", size=1)

df_gp2 <- bootvalues$group_centers[["group2"]]

melted_df <- reshape2::melt(df_gp2)
melted_df$variable <- as.factor(melted_df$variable)

ggplot() +
  geom_histogram(mapping = aes(x = value), data = melted_df, bins = 30) +
  labs(title = "stability of group 2 centers for OSM_PreFire_Neither", subtitle = "for 1000 iterations") +
  xlim(-3,3)+
  facet_wrap(vars(variable), ncol=3)+
  geom_vline(xintercept = 0.5, linetype="dotted", 
             color = "red", size=1)

df_gp3 <- bootvalues$group_centers[["group3"]]

melted_df <- reshape2::melt(df_gp3)
melted_df$variable <- as.factor(melted_df$variable)

ggplot() +
  geom_histogram(mapping = aes(x = value), data = melted_df, bins = 30) +
  labs(title = "stability of group 3 centers for OSM_PreFire_Neither", subtitle = "for 1000 iterations") +
  xlim(-3,3)+
  facet_wrap(vars(variable), ncol=3)+
  geom_vline(xintercept = 0.5, linetype="dotted", 
             color = "red", size=1)

df_gp4 <- bootvalues$group_centers[["group4"]]

melted_df <- reshape2::melt(df_gp4)
melted_df$variable <- as.factor(melted_df$variable)

ggplot() +
  geom_histogram(mapping = aes(x = value), data = melted_df, bins = 30) +
  labs(title = "stability of group 4 centers for OSM_PreFire_Neither", subtitle = "for 1000 iterations") +
  xlim(-3,3)+
  facet_wrap(vars(variable), ncol=3)+
  geom_vline(xintercept = 0.5, linetype="dotted", 
             color = "red", size=1)
```

# Remove temp files
```{r}
rm(DFmapping,FortiData,Undecided,SGFCMMaps,WMat,Neighbours,bootvalues,melted_df,df_gp1,df_gp2,df_gp3,df_gp4)
```

# Fire

```{r}
OSM_AnalysisFields <- c("avg_version","avg_NACount", "avg_datediff", "aeroway_count","amenity_count","barrier_count","boundary_count","building_count","emergency_count","highway_count","historic_count","landuse_count","leisure_count","man_made_count","natural_count","office_count","place_count","power_count","railway_count","route_count","shop_count","sport_count","tourism_count","water_count","waterway_count")

#rescaling the columns
OSM_Cluster_Poly_Fire_Neither <- OSM_Fire_Neither_Grids[OSM_AnalysisFields]

OSM_Cluster_Poly_Fire_Neither <- as_Spatial(OSM_Cluster_Poly_Fire_Neither)

OSM_Cluster_Fire_Neither <- OSM_Cluster_Poly_Fire_Neither@data[OSM_AnalysisFields]
for (Col in names(OSM_Cluster_Fire_Neither)){
  OSM_Cluster_Fire_Neither[[Col]] <- scale(OSM_Cluster_Fire_Neither[[Col]])
}

OSM_Cluster_Fire_Neither$aeroway_count <- 0
OSM_Cluster_Fire_Neither$amenity_count <- 0
OSM_Cluster_Fire_Neither$barrier_count <- 0
OSM_Cluster_Fire_Neither$boundary_count <- 0
OSM_Cluster_Fire_Neither$building_count <- 0
OSM_Cluster_Fire_Neither$emergency_count <- 0
OSM_Cluster_Fire_Neither$historic_count <- 0
OSM_Cluster_Fire_Neither$landuse_count <- 0
OSM_Cluster_Fire_Neither$leisure_count <- 0
OSM_Cluster_Fire_Neither$man_made_count <- 0
OSM_Cluster_Fire_Neither$office_count <- 0
OSM_Cluster_Fire_Neither$place_count <- 0
OSM_Cluster_Fire_Neither$power_count <- 0
OSM_Cluster_Fire_Neither$railway_count <- 0
OSM_Cluster_Fire_Neither$shop_count <- 0
OSM_Cluster_Fire_Neither$sport_count <- 0
OSM_Cluster_Fire_Neither$tourism_count <- 0
OSM_Cluster_Fire_Neither$water_count <- 0

Neighbours <- poly2nb(OSM_Cluster_Poly_Fire_Neither, queen = TRUE)
WMat <- nb2listw(Neighbours, style = "W", zero.policy = TRUE)

#preparing some elements for further mapping
OSM_Cluster_Poly_Fire_Neither$OID <- as.character(1:nrow(OSM_Cluster_Poly_Fire_Neither))

FortiData <- broom::tidy(OSM_Cluster_Poly_Fire_Neither,region="OID")

OSM_Cluster_Fire_Neither_SGFCM <- SGFCMeans(OSM_Cluster_Fire_Neither,WMat,k = 4,m=1.5, alpha=0.95, beta = 0.65,
                                          tol=0.0001, standardize = FALSE, verbose = FALSE, seed = 456)

SGFCMMaps <- mapClusters(geodata = OSM_Cluster_Poly_Fire_Neither, object = OSM_Cluster_Fire_Neither_SGFCM$Belongings,undecided = 0.45)
```

```{r}
ggarrange(SGFCMMaps$ProbaMaps[[1]], nrow = 1, ncol = 1,
          common.legend = TRUE, legend = "bottom")

ggarrange(SGFCMMaps$ProbaMaps[[2]], nrow = 1, ncol = 1,
          common.legend = TRUE, legend = "bottom")

ggarrange(SGFCMMaps$ProbaMaps[[3]], nrow = 1, ncol = 1,
          common.legend = TRUE, legend = "bottom")

ggarrange(SGFCMMaps$ProbaMaps[[4]], nrow = 1, ncol = 1,
          common.legend = TRUE, legend = "bottom")

# Final map
Undecided <- undecidedUnits(OSM_Cluster_Fire_Neither_SGFCM$Belongings,0.45)
OSM_Cluster_Poly_Fire_Neither$FinalCluster <- ifelse(Undecided=="Undecided",
                                                   "Undecided",paste("cluster",Undecided,sep="_"))

#mapping the groups
DFmapping <- merge(FortiData,OSM_Cluster_Poly_Fire_Neither,by.x="id",by.y="OID")

ggplot(data=DFmapping)+
  geom_polygon(aes(x=long,y=lat,group=group,fill=FinalCluster),color=rgb(0,0,0,0))+
  coord_fixed(ratio = 1)+
  ggtitle("OSM_Fire_Neither_FinalCluster") +
  scale_fill_manual(name="Clusters",values = c("cluster_V1"="palegreen3",
                                               "cluster_V2"="Firebrick",
                                               "cluster_V3"="yellow",
                                               "cluster_V4"="steelblue",
                                               "Undecided"=rgb(0,0,0,0.4)))+
  theme( axis.title = element_blank(),
         axis.text = element_blank(),
         axis.ticks = element_blank()
  )
```

```{r}
#summarizeClusters(OSM_Cluster_Fire_Neither,belongmatrix = OSM_Cluster_Fire_Neither_SGFCM$Belongings,
#                  weighted = TRUE, dec = 3)

spiderPlots(OSM_Cluster_Fire_Neither, OSM_Cluster_Fire_Neither_SGFCM$Belongings,
            chartcolors = c("palegreen3","Firebrick","yellow","steelblue"))
title("OSM_Fire_Neither clusters and input variables")
```

```{r}
bootvalues <- boot_group_validation(OSM_Cluster_Fire_Neither_SGFCM, nsim = 1000, maxiter = 1000, 
                                    tol = 0.0001, verbose = FALSE)

melted_df <- reshape2::melt(bootvalues$group_consistency)

melted_df$variable <- as.factor(melted_df$variable)

ggplot() +
  geom_histogram(mapping = aes(x = value), data = melted_df, bins = 30) +
  labs(title = "stability of clusters for OSM_Fire_Neither", subtitle = "for 1000 iterations",
       x = "Jaccard index") +
  facet_wrap(vars(variable), ncol=2) +
  geom_vline(xintercept = 0.5, linetype="dotted", 
             color = "red", size=1)
```

```{r, fig.width = 10, fig.height= 10}
# groups 2 and 4 raised as concerns 

df_gp1 <- bootvalues$group_centers[["group1"]]

melted_df <- reshape2::melt(df_gp1)

melted_df$variable <- as.factor(melted_df$variable)

ggplot() +
  geom_histogram(mapping = aes(x = value), data = melted_df, bins = 30) +
  labs(title = "stability of group 1 centers for OSM_Fire_Neither", subtitle = "for 1000 iterations") +
  xlim(-3,3)+
  facet_wrap(vars(variable), ncol=3)+
  geom_vline(xintercept = 0.5, linetype="dotted", 
             color = "red", size=1)

df_gp2 <- bootvalues$group_centers[["group2"]]

melted_df <- reshape2::melt(df_gp2)

melted_df$variable <- as.factor(melted_df$variable)

ggplot() +
  geom_histogram(mapping = aes(x = value), data = melted_df, bins = 30) +
  labs(title = "stability of group 2 centers for OSM_Fire_Neither", subtitle = "for 1000 iterations") +
  xlim(-3,3)+
  facet_wrap(vars(variable), ncol=3)+
  geom_vline(xintercept = 0.5, linetype="dotted", 
             color = "red", size=1)

df_gp3 <- bootvalues$group_centers[["group3"]]

melted_df <- reshape2::melt(df_gp3)

melted_df$variable <- as.factor(melted_df$variable)

ggplot() +
  geom_histogram(mapping = aes(x = value), data = melted_df, bins = 30) +
  labs(title = "stability of group 3 centers for OSM_Fire_Neither", subtitle = "for 1000 iterations") +
  xlim(-3,3)+
  facet_wrap(vars(variable), ncol=3)+
  geom_vline(xintercept = 0.5, linetype="dotted", 
             color = "red", size=1)

df_gp4 <- bootvalues$group_centers[["group4"]]

melted_df <- reshape2::melt(df_gp4)

melted_df$variable <- as.factor(melted_df$variable)

ggplot() +
  geom_histogram(mapping = aes(x = value), data = melted_df, bins = 30) +
  labs(title = "stability of group 4 centers for OSM_Fire_Neither", subtitle = "for 1000 iterations") +
  xlim(-3,3)+
  facet_wrap(vars(variable), ncol=3)+
  geom_vline(xintercept = 0.5, linetype="dotted", 
             color = "red", size=1)
```

```{r}
rm(DFmapping,FortiData,Undecided,SGFCMMaps,WMat,Neighbours,bootvalues,melted_df,df_gp1,df_gp2,df_gp3,df_gp4)
```

# Post Fire

```{r}
OSM_AnalysisFields <- c("avg_version","avg_NACount", "avg_datediff", "aeroway_count","amenity_count","barrier_count","boundary_count","building_count","emergency_count","highway_count","historic_count","landuse_count","leisure_count","man_made_count","natural_count","office_count","place_count","power_count","railway_count","route_count","shop_count","sport_count","tourism_count","water_count","waterway_count")

#rescaling the columns
OSM_Cluster_Poly_PostFire_Neither <- OSM_PostFire_Neither_Grids[OSM_AnalysisFields]

OSM_Cluster_Poly_PostFire_Neither <- as_Spatial(OSM_Cluster_Poly_PostFire_Neither)

OSM_Cluster_PostFire_Neither <- OSM_Cluster_Poly_PostFire_Neither@data[OSM_AnalysisFields]
for (Col in names(OSM_Cluster_PostFire_Neither)){
  OSM_Cluster_PostFire_Neither[[Col]] <- scale(OSM_Cluster_PostFire_Neither[[Col]])
}

OSM_Cluster_PostFire_Neither$aeroway_count <- 0
OSM_Cluster_PostFire_Neither$amenity_count <- 0
OSM_Cluster_PostFire_Neither$barrier_count <- 0
OSM_Cluster_PostFire_Neither$boundary_count <- 0
OSM_Cluster_PostFire_Neither$building_count <- 0
OSM_Cluster_PostFire_Neither$emergency_count <- 0
OSM_Cluster_PostFire_Neither$historic_count <- 0
OSM_Cluster_PostFire_Neither$landuse_count <- 0
OSM_Cluster_PostFire_Neither$leisure_count <- 0
OSM_Cluster_PostFire_Neither$man_made_count <- 0
OSM_Cluster_PostFire_Neither$office_count <- 0
OSM_Cluster_PostFire_Neither$place_count <- 0
OSM_Cluster_PostFire_Neither$power_count <- 0
OSM_Cluster_PostFire_Neither$railway_count <- 0
OSM_Cluster_PostFire_Neither$shop_count <- 0
OSM_Cluster_PostFire_Neither$sport_count <- 0
OSM_Cluster_PostFire_Neither$tourism_count <- 0
OSM_Cluster_PostFire_Neither$water_count <- 0

Neighbours <- poly2nb(OSM_Cluster_Poly_PostFire_Neither, queen = TRUE)
WMat <- nb2listw(Neighbours, style = "W", zero.policy = TRUE)

#preparing some elements for further mapping
OSM_Cluster_Poly_PostFire_Neither$OID <- as.character(1:nrow(OSM_Cluster_Poly_PostFire_Neither))

FortiData <- broom::tidy(OSM_Cluster_Poly_PostFire_Neither,region="OID")

OSM_Cluster_PostFire_Neither_SGFCM <- SGFCMeans(OSM_Cluster_PostFire_Neither,WMat,k = 4,m=1.5, alpha=0.95, beta = 0.65,
                                              tol=0.0001, standardize = FALSE, verbose = FALSE, seed = 456)

SGFCMMaps <- mapClusters(geodata = OSM_Cluster_Poly_PostFire_Neither, object = OSM_Cluster_PostFire_Neither_SGFCM$Belongings,undecided = 0.45)
```

```{r}
ggarrange(SGFCMMaps$ProbaMaps[[1]], nrow = 1, ncol = 1,
          common.legend = TRUE, legend = "bottom")

ggarrange(SGFCMMaps$ProbaMaps[[2]], nrow = 1, ncol = 1,
          common.legend = TRUE, legend = "bottom")

ggarrange(SGFCMMaps$ProbaMaps[[3]], nrow = 1, ncol = 1,
          common.legend = TRUE, legend = "bottom")

ggarrange(SGFCMMaps$ProbaMaps[[4]], nrow = 1, ncol = 1,
          common.legend = TRUE, legend = "bottom")

# Final map
Undecided <- undecidedUnits(OSM_Cluster_PostFire_Neither_SGFCM$Belongings,0.45)
OSM_Cluster_Poly_PostFire_Neither$FinalCluster <- ifelse(Undecided=="Undecided",
                                                       "Undecided",paste("cluster",Undecided,sep="_"))

#mapping the groups
DFmapping <- merge(FortiData,OSM_Cluster_Poly_PostFire_Neither,by.x="id",by.y="OID")

ggplot(data=DFmapping)+
  geom_polygon(aes(x=long,y=lat,group=group,fill=FinalCluster),color=rgb(0,0,0,0))+
  coord_fixed(ratio = 1)+
  ggtitle("OSM_PostFire_Neither_FinalCluster") +
  scale_fill_manual(name="Clusters",values = c("cluster_V1"="palegreen3",
                                               "cluster_V2"="Firebrick",
                                               "cluster_V3"="yellow",
                                               "cluster_V4"="steelblue",
                                               "Undecided"=rgb(0,0,0,0.4)))+
  theme( axis.title = element_blank(),
         axis.text = element_blank(),
         axis.ticks = element_blank()
  )
```

```{r}
#summarizeClusters(OSM_Cluster_PostFire_Neither,belongmatrix = OSM_Cluster_PostFire_Neither_SGFCM$Belongings,
#                  weighted = TRUE, dec = 3)

spiderPlots(OSM_Cluster_PostFire_Neither, OSM_Cluster_PostFire_Neither_SGFCM$Belongings,
            chartcolors = c("palegreen3","Firebrick","yellow","steelblue"))
title("OSM_PostFire_Neither clusters and input variables")
```

```{r}
bootvalues <- boot_group_validation(OSM_Cluster_PostFire_Neither_SGFCM, nsim = 1000, maxiter = 1000, 
                                    tol = 0.0001, verbose = FALSE)

melted_df <- reshape2::melt(bootvalues$group_consistency)

melted_df$variable <- as.factor(melted_df$variable)

ggplot() +
  geom_histogram(mapping = aes(x = value), data = melted_df, bins = 30) +
  labs(title = "stability of clusters for OSM_PostFire_Neither", subtitle = "for 1000 iterations",
       x = "Jaccard index") +
  facet_wrap(vars(variable), ncol=2) +
  geom_vline(xintercept = 0.5, linetype="dotted", 
             color = "red", size=1)
```

```{r, fig.width = 10, fig.height= 10}
# groups 2 and 4 raised as concerns 

df_gp1 <- bootvalues$group_centers[["group1"]]

melted_df <- reshape2::melt(df_gp1)

melted_df$variable <- as.factor(melted_df$variable)

ggplot() +
  geom_histogram(mapping = aes(x = value), data = melted_df, bins = 30) +
  labs(title = "stability of group 1 centers for OSM_PostFire_Neither", subtitle = "for 1000 iterations") +
  xlim(-3,3)+
  facet_wrap(vars(variable), ncol=3)+
  geom_vline(xintercept = 0.5, linetype="dotted", 
             color = "red", size=1)

df_gp2 <- bootvalues$group_centers[["group2"]]

melted_df <- reshape2::melt(df_gp2)

melted_df$variable <- as.factor(melted_df$variable)

ggplot() +
  geom_histogram(mapping = aes(x = value), data = melted_df, bins = 30) +
  labs(title = "stability of group 2 centers for OSM_PostFire_Neither", subtitle = "for 1000 iterations") +
  xlim(-3,3)+
  facet_wrap(vars(variable), ncol=3)+
  geom_vline(xintercept = 0.5, linetype="dotted", 
             color = "red", size=1)

df_gp3 <- bootvalues$group_centers[["group3"]]

melted_df <- reshape2::melt(df_gp3)

melted_df$variable <- as.factor(melted_df$variable)

ggplot() +
  geom_histogram(mapping = aes(x = value), data = melted_df, bins = 30) +
  labs(title = "stability of group 3 centers for OSM_PostFire_Neither", subtitle = "for 1000 iterations") +
  xlim(-3,3)+
  facet_wrap(vars(variable), ncol=3)+
  geom_vline(xintercept = 0.5, linetype="dotted", 
             color = "red", size=1)

df_gp4 <- bootvalues$group_centers[["group4"]]

melted_df <- reshape2::melt(df_gp4)

melted_df$variable <- as.factor(melted_df$variable)

ggplot() +
  geom_histogram(mapping = aes(x = value), data = melted_df, bins = 30) +
  labs(title = "stability of group 4 centers for OSM_PostFire_Neither", subtitle = "for 1000 iterations") +
  xlim(-3,3)+
  facet_wrap(vars(variable), ncol=3)+
  geom_vline(xintercept = 0.5, linetype="dotted", 
             color = "red", size=1)
```

```{r}
rm(DFmapping,FortiData,Undecided,SGFCMMaps,WMat,Neighbours,bootvalues,melted_df,df_gp1,df_gp2,df_gp3,df_gp4)
```